/**
 * Complete nationality options matching Vincere's 179 nationalities
 * Values use nationality demonyms (e.g., "British", "American") to match Vincere integration
 */
export const nationalityOptions = [
  { value: "", label: "Select nationality..." },
  { value: "Afghan", label: "Afghan" },
  { value: "Albanian", label: "Albanian" },
  { value: "Algerian", label: "Algerian" },
  { value: "American", label: "American" },
  { value: "Andorran", label: "Andorran" },
  { value: "Angolan", label: "Angolan" },
  { value: "Antiguan", label: "Antiguan" },
  { value: "Argentinean", label: "Argentinean" },
  { value: "Armenian", label: "Armenian" },
  { value: "Australian", label: "Australian" },
  { value: "Austrian", label: "Austrian" },
  { value: "Azerbaijani", label: "Azerbaijani" },
  { value: "Bahamian", label: "Bahamian" },
  { value: "Bahraini", label: "Bahraini" },
  { value: "Bangladeshi", label: "Bangladeshi" },
  { value: "Barbadian", label: "Barbadian" },
  { value: "Barbudans", label: "Barbudans" },
  { value: "Batswana", label: "Batswana" },
  { value: "Belarusian", label: "Belarusian" },
  { value: "Belgian", label: "Belgian" },
  { value: "Belizean", label: "Belizean" },
  { value: "Beninese", label: "Beninese" },
  { value: "Bhutanese", label: "Bhutanese" },
  { value: "Bolivian", label: "Bolivian" },
  { value: "Bosnian or Herzegovinian", label: "Bosnian or Herzegovinian" },
  { value: "Brazilian", label: "Brazilian" },
  { value: "British", label: "British" },
  { value: "Bruneian", label: "Bruneian" },
  { value: "Bulgarian", label: "Bulgarian" },
  { value: "Burkinan", label: "Burkinan" },
  { value: "Burmese", label: "Burmese" },
  { value: "Burundian", label: "Burundian" },
  { value: "Cabo Verdean", label: "Cabo Verdean" },
  { value: "Cambodian", label: "Cambodian" },
  { value: "Cameroonian", label: "Cameroonian" },
  { value: "Canadian", label: "Canadian" },
  { value: "Central African", label: "Central African" },
  { value: "Chadian", label: "Chadian" },
  { value: "Chilean", label: "Chilean" },
  { value: "Chinese", label: "Chinese" },
  { value: "Colombian", label: "Colombian" },
  { value: "Comoran", label: "Comoran" },
  { value: "Congolese (Congo)", label: "Congolese (Congo)" },
  { value: "Costa Rican", label: "Costa Rican" },
  { value: "Croatian", label: "Croatian" },
  { value: "Cuban", label: "Cuban" },
  { value: "Cypriot", label: "Cypriot" },
  { value: "Czech", label: "Czech" },
  { value: "Danish", label: "Danish" },
  { value: "Djiboutian", label: "Djiboutian" },
  { value: "Dominican", label: "Dominican" },
  { value: "Dutch", label: "Dutch" },
  { value: "Ecuadorean", label: "Ecuadorean" },
  { value: "Egyptian", label: "Egyptian" },
  { value: "Emirati", label: "Emirati" },
  { value: "Estonian", label: "Estonian" },
  { value: "Ethiopian", label: "Ethiopian" },
  { value: "Fijian", label: "Fijian" },
  { value: "Filipino", label: "Filipino" },
  { value: "Finnish", label: "Finnish" },
  { value: "French", label: "French" },
  { value: "Gabonese", label: "Gabonese" },
  { value: "Gambian", label: "Gambian" },
  { value: "Georgian", label: "Georgian" },
  { value: "German", label: "German" },
  { value: "Greek", label: "Greek" },
  { value: "Grenadian", label: "Grenadian" },
  { value: "Guatemalan", label: "Guatemalan" },
  { value: "Guinea-Bissauan", label: "Guinea-Bissauan" },
  { value: "Guinean", label: "Guinean" },
  { value: "Guyanese", label: "Guyanese" },
  { value: "Haitian", label: "Haitian" },
  { value: "Herzegovinian", label: "Herzegovinian" },
  { value: "Honduran", label: "Honduran" },
  { value: "Hungarian", label: "Hungarian" },
  { value: "Icelandic", label: "Icelandic" },
  { value: "Indian", label: "Indian" },
  { value: "Indonesian", label: "Indonesian" },
  { value: "Iranian", label: "Iranian" },
  { value: "Iraqi", label: "Iraqi" },
  { value: "Irish", label: "Irish" },
  { value: "Israeli", label: "Israeli" },
  { value: "Italian", label: "Italian" },
  { value: "Ivorian", label: "Ivorian" },
  { value: "Jamaican", label: "Jamaican" },
  { value: "Japanese", label: "Japanese" },
  { value: "Jordanian", label: "Jordanian" },
  { value: "Kazakhstani", label: "Kazakhstani" },
  { value: "Kenyan", label: "Kenyan" },
  { value: "Kiribati", label: "Kiribati" },
  { value: "Kuwaiti", label: "Kuwaiti" },
  { value: "Kyrgyzstani", label: "Kyrgyzstani" },
  { value: "Lao", label: "Lao" },
  { value: "Latvian", label: "Latvian" },
  { value: "Lebanese", label: "Lebanese" },
  { value: "Liberian", label: "Liberian" },
  { value: "Libyan", label: "Libyan" },
  { value: "Liechtenstein", label: "Liechtenstein" },
  { value: "Lithuanian", label: "Lithuanian" },
  { value: "Luxembourgish", label: "Luxembourgish" },
  { value: "Macedonian", label: "Macedonian" },
  { value: "Malagasy", label: "Malagasy" },
  { value: "Malawian", label: "Malawian" },
  { value: "Malaysian", label: "Malaysian" },
  { value: "Maldivian", label: "Maldivian" },
  { value: "Malian", label: "Malian" },
  { value: "Maltese", label: "Maltese" },
  { value: "Marshallese", label: "Marshallese" },
  { value: "Mauritanian", label: "Mauritanian" },
  { value: "Mauritian", label: "Mauritian" },
  { value: "Mexican", label: "Mexican" },
  { value: "Micronesian", label: "Micronesian" },
  { value: "Moldovan", label: "Moldovan" },
  { value: "Monacan", label: "Monacan" },
  { value: "Mongolian", label: "Mongolian" },
  { value: "Moroccan", label: "Moroccan" },
  { value: "Mozambican", label: "Mozambican" },
  { value: "Namibian", label: "Namibian" },
  { value: "Nepalese", label: "Nepalese" },
  { value: "New Zealander", label: "New Zealander" },
  { value: "Nicaraguan", label: "Nicaraguan" },
  { value: "Nigerian", label: "Nigerian" },
  { value: "North Korean", label: "North Korean" },
  { value: "Northern Irish", label: "Northern Irish" },
  { value: "Norwegian", label: "Norwegian" },
  { value: "Omani", label: "Omani" },
  { value: "Pakistani", label: "Pakistani" },
  { value: "Palauan", label: "Palauan" },
  { value: "Panamanian", label: "Panamanian" },
  { value: "Papua New Guinean", label: "Papua New Guinean" },
  { value: "Paraguayan", label: "Paraguayan" },
  { value: "Peruvian", label: "Peruvian" },
  { value: "Polish", label: "Polish" },
  { value: "Portuguese", label: "Portuguese" },
  { value: "Qatari", label: "Qatari" },
  { value: "Romanian", label: "Romanian" },
  { value: "Russian", label: "Russian" },
  { value: "Rwandan", label: "Rwandan" },
  { value: "Saint Lucian", label: "Saint Lucian" },
  { value: "Salvadoran", label: "Salvadoran" },
  { value: "Samoan", label: "Samoan" },
  { value: "San Marinese", label: "San Marinese" },
  { value: "Saudi", label: "Saudi" },
  { value: "Scottish", label: "Scottish" },
  { value: "Senegalese", label: "Senegalese" },
  { value: "Serbian", label: "Serbian" },
  { value: "Seychellois", label: "Seychellois" },
  { value: "Sierra Leonean", label: "Sierra Leonean" },
  { value: "Singaporean", label: "Singaporean" },
  { value: "Slovakian", label: "Slovakian" },
  { value: "Slovenian", label: "Slovenian" },
  { value: "Solomon Islander", label: "Solomon Islander" },
  { value: "Somali", label: "Somali" },
  { value: "South African", label: "South African" },
  { value: "South Korean", label: "South Korean" },
  { value: "Spanish", label: "Spanish" },
  { value: "Sri Lankan", label: "Sri Lankan" },
  { value: "Swazi", label: "Swazi" },
  { value: "Swedish", label: "Swedish" },
  { value: "Swiss", label: "Swiss" },
  { value: "Syrian", label: "Syrian" },
  { value: "Taiwanese", label: "Taiwanese" },
  { value: "Tanzanian", label: "Tanzanian" },
  { value: "Thai", label: "Thai" },
  { value: "Togolese", label: "Togolese" },
  { value: "Tongan", label: "Tongan" },
  { value: "Trinidadian or Tobagonian", label: "Trinidadian or Tobagonian" },
  { value: "Tunisian", label: "Tunisian" },
  { value: "Turkish", label: "Turkish" },
  { value: "Tuvaluan", label: "Tuvaluan" },
  { value: "Ugandan", label: "Ugandan" },
  { value: "Ukrainian", label: "Ukrainian" },
  { value: "Uruguayan", label: "Uruguayan" },
  { value: "Uzbekistani", label: "Uzbekistani" },
  { value: "Venezuelan", label: "Venezuelan" },
  { value: "Vietnamese", label: "Vietnamese" },
  { value: "Welsh", label: "Welsh" },
  { value: "Zambian", label: "Zambian" },
  { value: "Zimbabwean", label: "Zimbabwean" },
] as const;

export type CandidateType = "yacht_crew" | "household_staff" | "both" | "other";

export const candidateTypeOptions: Array<{ value: CandidateType; label: string }> = [
  { value: "yacht_crew", label: "Yacht Crew" },
  { value: "household_staff", label: "Household Staff" },
  { value: "both", label: "Both Yacht & Household" },
  { value: "other", label: "Other" },
];

// License options for yacht crew
export const licenseOptions = [
  { value: "", label: "No formal license" },
  { value: "stcw_basic", label: "STCW Basic Safety" },
  { value: "rya_yachtmaster_offshore", label: "RYA Yachtmaster Offshore" },
  { value: "rya_yachtmaster_ocean", label: "RYA Yachtmaster Ocean" },
  { value: "mca_oow", label: "MCA Officer of the Watch" },
  { value: "mca_chief_mate", label: "MCA Chief Mate" },
  { value: "master_200gt", label: "Master 200GT" },
  { value: "master_500gt", label: "Master 500GT" },
  { value: "master_3000gt", label: "Master 3000GT" },
  { value: "master_unlimited", label: "Master Unlimited" },
  { value: "y4_engineer", label: "Y4 Engineer" },
  { value: "y3_engineer", label: "Y3 Engineer" },
  { value: "y2_engineer", label: "Y2 Engineer" },
  { value: "y1_engineer", label: "Y1 Engineer" },
  { value: "chief_engineer_unlimited", label: "Chief Engineer Unlimited" },
  { value: "powerboat_level_2", label: "Powerboat Level 2" },
  { value: "pwc_license", label: "Personal Watercraft License" },
] as const;

// Certification checklist options organized by category
export const certificationChecklistOptions = [
  // STCW Category
  {
    type: "stcw_firefighting",
    label: "STCW Advanced Firefighting",
    category: "STCW",
  },
  {
    type: "stcw_medical_first_aid",
    label: "STCW Medical First Aid",
    category: "STCW",
  },
  {
    type: "stcw_medical_care",
    label: "STCW Medical Care",
    category: "STCW",
  },

  // Food & Service
  {
    type: "food_hygiene_l2",
    label: "Food Hygiene Level 2",
    category: "Food & Service",
  },
  {
    type: "food_hygiene_l3",
    label: "Food Hygiene Level 3",
    category: "Food & Service",
  },
  {
    type: "silver_service",
    label: "Silver Service",
    category: "Food & Service",
  },

  // Wine & Spirits
  {
    type: "wset_l1",
    label: "WSET Level 1",
    category: "Wine & Spirits",
  },
  {
    type: "wset_l2",
    label: "WSET Level 2",
    category: "Wine & Spirits",
  },
  {
    type: "wset_l3",
    label: "WSET Level 3",
    category: "Wine & Spirits",
  },

  // Medical
  {
    type: "first_aid",
    label: "First Aid Certificate",
    category: "Medical",
  },

  // Water Sports & Diving
  {
    type: "powerboat_l2",
    label: "Powerboat Level 2",
    category: "Water Sports",
  },
  {
    type: "pwc_license",
    label: "Personal Watercraft License",
    category: "Water Sports",
  },
  {
    type: "padi_open_water",
    label: "PADI Open Water",
    category: "Diving",
  },
  {
    type: "padi_advanced",
    label: "PADI Advanced Open Water",
    category: "Diving",
  },
  {
    type: "padi_divemaster",
    label: "PADI Divemaster",
    category: "Diving",
  },
  {
    type: "dive_instructor",
    label: "Dive Instructor (PADI/SSI)",
    category: "Diving",
  },
  {
    type: "water_sports_instructor",
    label: "Water Sports Instructor",
    category: "Water Sports",
  },

  // RYA
  {
    type: "rya_certifications",
    label: "RYA Certifications",
    category: "RYA",
  },

  // Fitness & Wellness
  {
    type: "personal_trainer",
    label: "Personal Trainer Certification",
    category: "Fitness",
  },
  {
    type: "yoga_instructor",
    label: "Yoga Instructor",
    category: "Wellness",
  },
  {
    type: "massage_therapist",
    label: "Massage Therapist License",
    category: "Wellness",
  },

  // Other
  {
    type: "other",
    label: "Other (specify)",
    category: "Other",
    allowCustom: true,
  },
] as const;

// Gender options (restricted to Male/Female as per requirements)
export const genderOptions = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
] as const;

// Profile wizard steps
export type ProfileStep = "personal" | "professional" | "certifications" | "details" | "complete";

export const profileSteps: ProfileStep[] = [
  "personal",
  "professional",
  "certifications",
  "details",
  "complete",
];

// Step metadata
export const stepMetadata = {
  personal: {
    title: "Personal Information",
    description: "Basic personal details and contact information",
  },
  professional: {
    title: "Professional Details",
    description: "Your position, licenses, and experience",
  },
  certifications: {
    title: "Certifications & Visas",
    description: "Professional certifications and visa status",
  },
  details: {
    title: "Personal Details",
    description: "Additional personal information",
  },
  complete: {
    title: "Profile Complete",
    description: "Review and complete your profile",
  },
} as const;
