-- Migration: Cleanup old document embeddings and extracted text
-- When documents are marked as not the latest version, we should:
-- 1. Clear extracted_text (saves storage, no longer needed)
-- 2. Clear embedding (saves storage, no longer used for matching)
-- 3. Keep file_url and other metadata (for audit/history in agency dashboard)

-- Update the create_document_version function to clear old data
CREATE OR REPLACE FUNCTION create_document_version(
  p_parent_document_id UUID,
  p_new_file_url TEXT,
  p_new_file_path TEXT,
  p_new_file_size INTEGER,
  p_new_mime_type TEXT,
  p_uploaded_by UUID,
  p_organization_id UUID
)
RETURNS UUID AS $$
DECLARE
  v_parent RECORD;
  v_new_doc_id UUID;
  v_new_version INTEGER;
BEGIN
  -- Get parent document details
  SELECT * INTO v_parent
  FROM documents
  WHERE id = p_parent_document_id
    AND deleted_at IS NULL;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Parent document not found or has been deleted';
  END IF;

  -- Calculate new version number
  v_new_version := v_parent.version + 1;

  -- Mark all previous versions as not latest AND clear their extracted data
  UPDATE documents
  SET
    is_latest_version = FALSE,
    extracted_text = NULL,  -- Clear old text extraction
    embedding = NULL        -- Clear old embedding
  WHERE entity_type = v_parent.entity_type
    AND entity_id = v_parent.entity_id
    AND type = v_parent.type
    AND is_latest_version = TRUE
    AND deleted_at IS NULL;

  -- IMPORTANT: Invalidate the candidate's embedding to prevent stale search results
  -- The embedding will be regenerated by the embedding worker when the new CV text is extracted
  IF v_parent.entity_type = 'candidate' AND v_parent.type = 'cv' THEN
    UPDATE candidates
    SET
      embedding = NULL,
      embedding_text = NULL,
      embedding_updated_at = NOW()
    WHERE id = v_parent.entity_id;
  END IF;

  -- Create new version
  INSERT INTO documents (
    entity_type,
    entity_id,
    type,
    name,
    description,
    file_url,
    file_path,
    file_size,
    mime_type,
    version,
    parent_document_id,
    is_latest_version,
    status,
    uploaded_by,
    organization_id,
    expiry_date,
    metadata
  ) VALUES (
    v_parent.entity_type,
    v_parent.entity_id,
    v_parent.type,
    v_parent.name || ' (v' || v_new_version::text || ')',
    v_parent.description,
    p_new_file_url,
    p_new_file_path,
    p_new_file_size,
    p_new_mime_type,
    v_new_version,
    p_parent_document_id,
    TRUE,
    'pending',
    p_uploaded_by,
    p_organization_id,
    v_parent.expiry_date,
    v_parent.metadata
  )
  RETURNING id INTO v_new_doc_id;

  RETURN v_new_doc_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Update the embedding trigger to only fire for latest versions
-- This prevents unnecessary queue operations for old document versions
DROP TRIGGER IF EXISTS trg_queue_embedding_on_document ON documents;
CREATE TRIGGER trg_queue_embedding_on_document
  AFTER INSERT OR UPDATE OF extracted_text, type
  ON documents
  FOR EACH ROW
  WHEN (NEW.entity_type = 'candidate' AND NEW.is_latest_version = TRUE)
  EXECUTE FUNCTION queue_candidate_embedding_on_document();

-- Backfill: Clear extracted_text and embedding from all old document versions
-- This is a one-time cleanup of existing data
UPDATE documents
SET
  extracted_text = NULL,
  embedding = NULL
WHERE is_latest_version = FALSE
  AND deleted_at IS NULL
  AND (extracted_text IS NOT NULL OR embedding IS NOT NULL);

-- Add comment explaining the approach
COMMENT ON FUNCTION create_document_version IS
  'Creates a new version of a document. Marks old versions as is_latest_version=FALSE and clears their extracted_text and embedding to save storage. File URLs and metadata are preserved for audit history.';
